buildbarn/bb-storage

WORKSPACE
Updated to latest version of the rule as it currently breaks with the latest bazel:
https://gitlab.com/remote-apis-testing/remote-apis-testing/-/jobs/232772464
=> Updated io_bazel_rules_go to 0.18.3

.github/workflows/CI.yaml, WORKSPACE, pkg/proto/configuration/blobstore/BUILD.bazel, pkg/proto/configuration/blobstore/blobstore.proto
Instead of having separate containers that do a 'go get' to obtain these
tools, fetch all of them through the Bazel workspace. This ensures that
we always stick to a fixed version.
=> Enable more autoformatters on our codebase

pkg/blobstore/remote_blob_access.go
A http error code was not handled correctly, which could make the client
think that a CAS blob was successfully uploaded, when in fact the upload
failed.  This could lead to subsequent AC entries referencing non-existing
CAS blobs.
=> Handle http error codes from PUT in http backend

pkg/grpc/BUILD.bazel, pkg/grpc/grpc.go
Just a small usability improvement for those of us using [grpcurl](https://github.com/fullstorydev/grpcurl):
```
$ grpcurl -plaintext localhost:8981 list
build.bazel.remote.execution.v2.ActionCache
build.bazel.remote.execution.v2.Capabilities
build.bazel.remote.execution.v2.ContentAddressableStorage
build.bazel.remote.execution.v2.Execution
google.bytestream.ByteStream
grpc.reflection.v1alpha.ServerReflection
$ grpcurl -plaintext localhost:8981 describe build.bazel.remote.execution.v2.ActionCache
build.bazel.remote.execution.v2.ActionCache is a service:
service ActionCache {
rpc GetActionResult ( .build.bazel.remote.execution.v2.GetActionResultRequest ) returns ( .build.bazel.remote.execution.v2.ActionResult ) {
option (.google.api.http) = { …
```
=> Support grpc reflection

WORKSPACE
This is the latest release at the time of writing, and contains a change
that allows the container puller to work with the http(s)_proxy environment
variable (commit bazelbuild/rules_docker@66e5e1a894e, "Add http(s)_proxy env
var support to puller (#1359)").
=> Update rules_docker to 0.14.1.

pkg/blobstore/cloud_blob_access.go
Fixes a bug where CloudBlobAccess would cause OOM when pushing large artifacts, thanks to a `buffer.ToReader` call pulling the entire blob into memory.
Uses a ChunkReader instead, and reads/writes in chunks. I wanted to avoid setting a flag to check if EOF was reached, but I couldn't find a way to (probably due to this being my first go patch).
Closes #50
=> CloudBlobAccess: Use Buffer API for Put

pkg/ac/action_cache_server.go
The text of the error is inverted from the actual test.
Also change the error code to reflect the intent.
=> Correct lies in error message

pkg/grpc/BUILD.bazel, pkg/grpc/grpc.go, pkg/proto/configuration/grpc/grpc.proto
This is used with a probe like
https://github.com/grpc-ecosystem/grpc-health-probe or
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#envoy-api-msg-core-healthcheck-grpchealthcheck
to determine whether a service is both healthy and the correct
service. It is typically deployed as a load balancer health check, to
handle the scenario where:
1. Our service is running on 1.2.3.4:8981
2. Our service is rescheduled to run on 2.3.4.5:8981
3. A different grpc server is started on 1.2.3.4:8981
Named service health checks allow the load balancer to notice that it
has the wrong backend, and not send it any rpcs.
In a future iteration, we should also redesign the API in this package
so that the various services can annnounce when they are ready to
serve traffic, for …
=> Add support for grpc health check protocol

pkg/cas/blob_access_content_addressable_storage.go, pkg/filesystem/BUILD.bazel, pkg/filesystem/directory.go, pkg/filesystem/local_directory.go, pkg/filesystem/local_directory_test.go
Add UtimesNano to directory interface to allow setting the mtime of files in the directory.
=> Add Utimes to directory interface

internal/mock/BUILD.bazel, pkg/filesystem/directory.go, pkg/filesystem/local_directory_darwin.go, pkg/filesystem/local_directory_linux.go
Allows Mknod to be called on linux, on darwin this will give a fixed error as this operation will not work.
This is needed for a patch to bb-remote-execution to allow installation of device nodes in the input root of the action being run.
=> Adds Mknod() to filesystem.Directory

README.md
This replaces the no-longer supported verifyActionResultCompleteness field with a completenessChecking wrapper/decorator in the configuration example.
=> Fix completeness checking example

pkg/grpc/BUILD.bazel, pkg/grpc/add_metadata_interceptor.go, pkg/grpc/add_metadata_interceptor_test.go, pkg/grpc/grpc.go, pkg/proto/configuration/grpc/grpc.proto
This change allows to specify custom headers in grpc metadata in blobstore configuration, for example 
```
blobstore: {
contentAddressableStorage: {
grpc: {
address: "remote.cache.tld:443",
metadata: [
{
header: "authorization",
values: [ "Bearer tokenXXXXXXXXXXXX" ]
},
...
```
This might be useful in case if builbarn is used as remote cache frontend which requires specific metadata like auth headers.
=> Add support for metadata in gRPC client configuration

pkg/proto/configuration/grpc/grpc.proto
Moving this clarification note into `grpc.proto` per suggestion in https://github.com/buildbarn/bb-remote-execution/pull/60#pullrequestreview-428661061
=> Add a clarification note about the forward_metadata in the grpc.proto

pkg/filesystem/local_directory.go
As discussed in https://github.com/buildbarn/bb-storage/issues/71 we're encountering issues when running TestLocalDirectoryEnterSymlink on our RHEL7 system (3.10.0-1127.8.2.el7.x86_64 Linux Kernel). Specifying O_PATH as a flag for openat solves this issue.
=> Return ENOTDIR instead of ELOOP when working with older Linux versions

pkg/blobstore/local/hashing_digest_location_map.go
Need to check key.Attempts, not the record that we're looking at, or else it could get into an infinite loop
=> Fix DLM Get

go.mod, go.sum, go_dependencies.bzl, pkg/global/BUILD.bazel, pkg/global/apply_configuration.go, pkg/proto/configuration/global/global.proto
Basic implementation of stackdriver tracing.
Should we extract common fields (like always sample) into a separate structure?
Should we shove this kind of thing under a tracing or debugging field with the jaeger stuff?
I punted on those for now cause it'd be a breaking config change, but more then happy to rework them
=> Add stackdriver trace

WORKSPACE
Necessary for compatibility with latest bazel.
=> Update rules_docker to latest

pkg/blobstore/configuration/new_blob_access.go, pkg/blobstore/redis_blob_access.go, pkg/blobstore/redis_blob_access_test.go, pkg/proto/configuration/blobstore/blobstore.proto
key_ttl is FIFO eviction, which is just about the worst eviction behaviour we can achieve
=> remove key_ttl from redis, it is worse than redis eviction

pkg/proto/configuration/blobstore/blobstore.proto
This should make it easier to find. Pulled from https://github.com/buildbarn/bb-storage/blob/ea0ae7cb574af99b1aac53b6b4d547b0a2262f16/pkg/blobstore/local/old_current_new_location_blob_map.go#L34
I changed some wording in the first paragraph to make more sense for the proto. Otherwise should be unchanged.
=> Add local blob storage comment to proto file

pkg/grpc/base_client_factory.go, pkg/grpc/server.go, pkg/proto/configuration/grpc/grpc.proto
In my struggle to understand/optimize cache performance, I added these as configuration options to pass through to grpc.  I'm not sure if they make a difference or not, or if anyone else would use them, but cost in code is slight and will at least document here for anyone else troubleshooting.  Take or leave at your pleasure.
See also:
* https://github.com/jlaxson/bb-storage/pull/new/add-grpc-window-size
* https://pkg.go.dev/google.golang.org/grpc#WithInitialConnWindowSize and friends
=> Add configurable window size

patches/com_github_bazelbuild_remote_apis/golang.diff
As a followup to #117 and to enable buildbarn/bb-remote-asset#24 to pass the linters.  This _could_ be separate but that seems excessive given these files already have to be patched here.
=> Also rename remote-asset target

pkg/proto/configuration/blobstore/blobstore.proto
google.protobuf.Duration's JSON behavior is not super intuitive so updating the example to be reflective of real usage will hopefully save someone some time
=> Update documentation for minimum_epoch_interval

WORKSPACE
It seems like only a small change is required in order to compile on darwin_arm64 i.e Apple M1 HW.
The node package supports darwin_arm64 from version 16+ so this PR will increment the node_version
to the latest supported version by the currently pointed out rules_nodejs.
The same change will also need to be made in the bb-remote-execution repository but I suppose
this should go in first and then a bump of the go_dependencies in the bb-remote-execution after that.
=> Add support for compiling on Apple M1

pkg/builder/configuration.go, pkg/builder/demultiplexing_build_queue.go, pkg/builder/demultiplexing_build_queue_test.go
Without forwarding of the gRPC context, authentication context gets lost. This can, for example, lead to failing calls to `GetCapabilities`, even when bb-storage is configured without any scheduler.
=> Forward gRPC context in the demultiplexing build queue

pkg/global/graceful_termination_handler.go
remote-apis-testing shows the following log in https://gitlab.com/remote-apis-testing/remote-apis-testing/-/jobs/2773967861
```
2022/07/26 20:20:14 Received terminated signal. Initiating graceful shutdown.
2022/07/26 20:20:14 Graceful shutdown complete
panic: Raising the original signal didn't cause us to shut down
```
Apparently, the panic line was reached before the signal had been handled and the process killed, so just remove it.
=> Remove panic after graceful shutdown

cmd/bb_replicator/main.go, cmd/bb_storage/main.go, pkg/grpc/server.go
The healthy and serving status, i.e. HTTP `/-/healthy` and `grpc_health_v1.HealthCheckResponse_SERVING`, will now be postponed until the whole service is up and running. Before, the healthy status was potentially reported before starting to listen to the gRPC ports.
This removes an error mode where Kubernetes would believe that the service was ready just before it crashed. The previous behaviour could lead to a cluster being upgraded to an erroneous state even for a simple jsonnet configuration error.
(I think this was the problem, don't remember exactly how it did behave.)
=> Postpone healthy service status response a bit

pkg/blobstore/configuration/new_blob_access.go, pkg/blobstore/local/block_device_backed_block_allocator.go, pkg/blobstore/local/block_device_backed_block_allocator_test.go
Various `buildbarn_blobstore_block_device_backed_block_allocator*` metrics had the missing storage_type metric, which meant that various storage types were being combined together.
Closes #138
=> Add missing storage_type metric label to various blobstore metrics

pkg/blobstore/configuration/new_blob_access.go
Consider a misconfiguration as follows:
persistent: {}
Before this misconfiguration would give the same error as if it was configured but had filesystem problems.
storage-0_1                 | 2023/03/14 10:13:51
Failed to create Content Addressable Storage: rpc error: code = Unknown
desc = Failed to open persistent state directory: no such file or directory
By writing the path in the error message, the error will hopefully be easier to track down.
=> Improve configuration error message for persistent directory

patches/com_github_bazelbuild_remote_apis/golang.diff
This change modifies the patch to the `bazelbuild/remote-apis` repo to also (re)generate code for `remote_asset.proto`, so that bazelbuild/bb-remote-asset can share this patch, and use a library built from codegen run with a recent (and patched) version of protoc-gen-go (that generates types that takes a `ServiceRegistrar` in generated `Register*` methods instead of a concrete `*grpc.Server`).
Tested: `bazel test //...` still passes on my system
=> build: Modify patch to remote-apis for greater compatibility

pkg/blobstore/readfallback/BUILD.bazel, pkg/blobstore/readfallback/read_fallback_blob_access.go, pkg/blobstore/readfallback/read_fallback_blob_access_test.go
The changes are very similar to mirroredBlobAccess
=> Add replication for missing blobs in readFallbackBlobAccess

BUILD.bazel, go_dependencies.bzl, patches/org_golang_x_sys/golang-issue-59357.diff, pkg/filesystem/directory.go, pkg/filesystem/local_directory_darwin.go, pkg/filesystem/local_directory_freebsd.go, pkg/filesystem/local_directory_linux.go, pkg/filesystem/local_directory_unix.go, pkg/filesystem/local_directory_windows.go
This is needed for 'chroot' runners that must mount the special filesystems '/proc' and '/sys' in the input root.
https://github.com/buildbarn/bb-remote-execution/issues/115
=> Add mount functionality to 'Directory'

WORKSPACE, cmd/bb_copy/BUILD.bazel, cmd/bb_replicator/BUILD.bazel, cmd/bb_storage/BUILD.bazel, tools/BUILD.bazel, tools/container.bzl, tools/github_workflows/workflows_template.libsonnet
Allows bb-storage users to deploy on arm64 architecture, e.g. AWS Graviton. Fixes #198
=> feat: publish multi-arch images

tools/BUILD.bazel
Fixes broken release step on master https://github.com/buildbarn/bb-storage/actions/runs/8426759325/job/23075783496
broken by #199 
Example of use showing correct interpolation: https://github.com/aspect-build/bazel-lib/blob/0fc838839c41677b18245152ad50759233c53794/lib/tests/expand_template/BUILD.bazel#L11
And if you're curious, the code is here: https://github.com/aspect-build/bazel-lib/blob/0fc838839c41677b18245152ad50759233c53794/tools/expand_template/main.go#L48
=> fix: release stamping needs double curlies

MODULE.bazel.lock, pkg/blobstore/configuration/BUILD.bazel, pkg/blobstore/configuration/new_blob_access.go, pkg/filesystem/BUILD.bazel, pkg/filesystem/local_directory_test.go, pkg/filesystem/local_directory_unix.go, pkg/filesystem/local_directory_windows.go, pkg/filesystem/path/BUILD.bazel, pkg/filesystem/path/absolute_scope_walker.go, pkg/filesystem/path/absolute_scope_walker_test.go, pkg/filesystem/path/builder.go, pkg/filesystem/path/builder_test.go, pkg/filesystem/path/component.go, pkg/filesystem/path/component_walker.go, pkg/filesystem/path/local_unix.go, pkg/filesystem/path/local_windows.go, pkg/filesystem/path/loop_detecting_scope_walker.go, pkg/filesystem/path/loop_detecting_scope_walker_test.go, pkg/filesystem/path/relative_scope_walker.go, pkg/filesystem/path/relative_scope_walker_test.go, pkg/filesystem/path/resolve_test.go, pkg/filesystem/path/scope_walker.go, pkg/filesystem/path/stringer.go, pkg/filesystem/path/trace.go, pkg/filesystem/path/trace_test.go, pkg/filesystem/path/unix_parser.go, pkg/filesystem/path/virtual_root_scope_walker_factory.go, pkg/filesystem/path/virtual_root_scope_walker_factory_test.go, pkg/filesystem/path/void_scope_walker.go, pkg/filesystem/path/windows_parser.go
This PR is identical to #206, but with the review comments addressed.
Fixes: #206
=> Add proper parsing/emitting of Windows style paths

.github/workflows/master.yaml, .github/workflows/pull-requests.yaml, tools/github_workflows/workflows_template.libsonnet
bb-portal uses gqlgen to generate code for graphql schemas using gqlgen. This tool will write embed statements in this format: //go:embed "schema/scalars.graphql" "schema/ent.graphql" "schema/custom.graphql". This is the offending file: https://github.com/buildbarn/bb-portal/blob/89b62a963a047b852cfc05723452922560611588/internal/graphql/server_gen.go#L1165
Rather than fight with this code generation tool, we can update the "embedded asset generation" workflow step to handle this format. This will just grab the first file that is listed and process that, which is a bit hacky, but it should work for now.
=> Update asset generation to support //go:embed statements listing multiple files

tools/github_workflows/workflows_template.libsonnet
bb-portal needs to build with cgo, due to a dependency on sqlite. This will let us generate workflows using the rules_go cgo platforms.
=> Extend workflows_template.libsonnet to make it possible to select cgo platforms

MODULE.bazel, patches/org_golang_x_sys/o-search.diff, pkg/filesystem/local_directory_darwin.go, pkg/filesystem/local_directory_freebsd.go, pkg/filesystem/local_directory_linux.go, pkg/filesystem/local_directory_unix.go
Right now we open directories using O_RDONLY. This is problematic, because it means we can't perform operations on directories that only have execute permissions. The solution for this is to use O_SEARCH, which was added in POSIX 2008.
Linux doesn't offer O_SEARCH, but we can emulate it using O_PATH. macOS has supported this feature since Ventura (October 2022).
=> Open directories using O_SEARCH

pkg/blobstore/replication/BUILD.bazel, pkg/blobstore/replication/metrics_blob_replicator.go, pkg/blobstore/replication/metrics_blob_replicator_test.go
The storage type label is missing from metrics blob replicator, causing the initialization to fail on: 
panic: 1 unknown label(s) found during currying
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*HistogramVec).MustCurryWith(...)
external/gazelle~~go_deps~com_github_prometheus_client_golang/prometheus/histogram.go:1278
Also, add a unit test to catch this case.
=> add missing label on replicator metrics and unit test

pkg/blobstore/replication/metrics_blob_replicator.go, pkg/blobstore/replication/metrics_blob_replicator_test.go
^, adding grpc code so it will be captured along with the duration.
=> add grpc code to metrics replicator

MODULE.bazel, MODULE.bazel.lock
Updates distroless/static to latest to pull in tzdata security update described here: https://lwn.net/Articles/1000160/
=> chore: update distroless/static to latest

pkg/http/oidc_authenticator.go, pkg/http/oidc_authenticator_test.go
Instead of returning a 303 (See Other) with a redirect to the OIDC login page, we return a 401 (Unauthorized) to the XHR request. This makes it easier for a web client to handle authentication errors.
=> Return 401 for XHR requests when not authenticated with OIDC

tools/container.bzl
It should be possible for others to make Bazel projects that depend on these images. For example, one may use rules_gitops to easily roll out Buildbarn container images on a Kubernetes cluster.
=> Make all container images public

pkg/util/tls_test.go
On Windows this fails with a slightly different error message:
Failed to configure server TLS: Failed to initialize certificate:
Failed to read certificate file: open /missing-cert.pem:
The system cannot find the file specified.
This slightly weakens the test but it still checks the message is reasonably helpful.
=> Fix the TLS test on windows

pkg/otel/BUILD.bazel
Before this it would fail with errors such as:
FATAL: aspect_rules_js[js_binary]: the entry_point
'/d/b/s9/nr2w6eog/execroot/_main/bazel-out/x64_windows-fastbuild/bin
/node_modules/.aspect_rules_js/purgecss@6.0.0/node_modules/purgecss/
bin/purgecss.js' not found
=> Make //pkg/otel build on Windows

pkg/filesystem/BUILD.bazel, pkg/filesystem/local_directory_test.go, pkg/filesystem/local_directory_windows.go, pkg/filesystem/local_directory_windows_test.go, pkg/filesystem/path/builder.go, pkg/filesystem/path/builder_test.go, pkg/filesystem/path/stringer.go, pkg/filesystem/path/trace.go, pkg/filesystem/path/trace_test.go, pkg/filesystem/path/windows_format.go
This provides a neater way of constructing NT device paths which are required for some system calls (e.g. creation of symlinks).
=> Improve pretty printing of Windows-style paths

pkg/blockdevice/new_block_device_from_file_windows.go
Whilst writing the integration test for buildbarn in bb-deployments, I noticed that bb_storage took a long time to shutdown on Windows. When looking at the system monitor, bb_storage was saturating the disk writing out data on shutdown. This was unexpected, since the test only wrote a small amount of data to the cache, so only a small amount of the block device should have been used (hundreds of MBs out of the GBs in the block device).
It seems that when using SetEndOfFile, Windows will write out the entire file's contents when the process gets shutdown. This is a problem if buildbarn is started with a large block device but only uses a small part of it, like in the deployment tests.
Following the suggestions at https://devblogs.microsoft.com/oldnewthing/20110922-00/?p=9573 we now create …
=> Fix a windows performance issue when shutting down block devices

pkg/jmespath/BUILD.bazel, pkg/jmespath/expression.go, pkg/jmespath/expression_test.go
It seems that using reflect.DeepEqual on protobuf messages doesn't work correctly; seemingly equal things are different because of internal protobuf fields.
This switches the comparison to use the protocmp library which does proper equality comparison. I've also extended the test cases to cover this.
=> Fix test vector comparison
